#!/usr/bin/env bash
# sync-memory.sh — Mem0 ↔ Obsidian sync. Closes KI-002 "not fully solved" gap.
#
# Direction: Mem0 (structured facts) → Obsidian (human-readable view).
# This is a one-way export: Mem0 is the source of truth for agent-readable facts;
# Obsidian is for human review. Edits in Obsidian do NOT write back to Mem0.
#
# Usage:
#   ./scripts/sync-memory.sh --user-id myproject
#   ./scripts/sync-memory.sh --user-id myproject --all
#   ./scripts/sync-memory.sh --user-id myproject --since 7   # days
#
# Requires: mem0 CLI, write access to GRAPHIFY_OBSIDIAN_PATH or ~/obsidian-vault/
set -u

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC}  $1"; }
fail() { echo -e "${RED}✗${NC} $1"; }
info() { echo -e "${BLUE}→${NC} $1"; }

USER_ID=""
ALL=false
SINCE_DAYS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --user-id) USER_ID="$2"; shift 2 ;;
    --all)     ALL=true; shift ;;
    --since)   SINCE_DAYS="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 --user-id <project> [--all] [--since <days>]"
      echo "  --user-id  Mem0 project scope (required)"
      echo "  --all      Export all memories (default: recent only)"
      echo "  --since N  Only memories from last N days"
      exit 0 ;;
    *) fail "Unknown arg: $1"; exit 1 ;;
  esac
done

[ -z "$USER_ID" ] && { fail "Required: --user-id <project>"; exit 1; }

# Resolve vault path
VAULT="${GRAPHIFY_OBSIDIAN_PATH:-$HOME/obsidian-vault}"
MEM_DIR="$VAULT/mem0-export/$USER_ID"
mkdir -p "$MEM_DIR" || { fail "Cannot create $MEM_DIR — check vault path"; exit 1; }

if ! command -v mem0 &>/dev/null; then
  fail "mem0 CLI not installed — run: npm install -g @mem0/cli"
  exit 1
fi

if ! curl -s http://localhost:3000/health &>/dev/null; then
  fail "Mem0 server not running on :3000 — run: docker compose up -d mem0"
  exit 1
fi

info "Syncing Mem0 → Obsidian for user-id: $USER_ID"

# Fetch memories. mem0 list outputs structured entries.
OUTFILE="$MEM_DIR/memories-$(date +%Y-%m-%d).md"

{
  echo "# Mem0 export — $USER_ID"
  echo ""
  echo "> Auto-generated by devstrata sync-memory.sh on $(date)"
  echo "> Source: Mem0 (localhost:3000), user-id: \`$USER_ID\`"
  echo "> Direction: one-way export. Do not edit here expecting sync back."
  echo ""
  if [ "$ALL" == "true" ]; then
    mem0 list --user-id "$USER_ID" 2>/dev/null
  elif [ -n "$SINCE_DAYS" ]; then
    # Best-effort: mem0 list doesn't have a --since flag in all versions.
    # Filter by date in the output if the CLI supports it; otherwise warn.
    mem0 list --user-id "$USER_ID" 2>/dev/null | \
      python3 -c "
import sys, re
from datetime import datetime, timedelta
cutoff = datetime.now() - timedelta(days=int('$SINCE_DAYS'))
for line in sys.stdin:
    print(line, end='')
    # NOTE: real date filtering requires mem0 to expose created_at.
    # This is a placeholder — adjust when mem0 list --since is supported.
" 2>/dev/null || mem0 list --user-id "$USER_ID" 2>/dev/null
    warn "--since is best-effort (mem0 CLI date filtering may be limited)"
  else
    mem0 list --user-id "$USER_ID" 2>/dev/null
  fi
} > "$OUTFILE"

LINES=$(wc -l < "$OUTFILE" | tr -d ' ')
# The header (title + meta + blank lines) is ~7 lines. Real memories come after.
# If we only have the header, the export is effectively empty.
HEADER_LINES=7
if [ "$LINES" -le "$HEADER_LINES" ]; then
  warn "Export is header-only ($LINES lines) — no memories found for user-id '$USER_ID'"
  warn "Is this the right user-id? Check: mem0 list --user-id $USER_ID"
  # Still keep the file (header only) so the user can see it ran, but mark it
  echo "<!-- No memories found for user-id '$USER_ID' on $(date) -->" >> "$OUTFILE"
  # Don't update the index if there's nothing to index (avoid noise)
  rm -f "$OUTFILE"
  exit 0
elif [ "$LINES" -gt 5 ]; then
  ok "Exported to $OUTFILE ($LINES lines)"
  # Update the index so Obsidian's Dataview can find it
  INDEX="$VAULT/mem0-export/INDEX.md"
  if [ ! -f "$INDEX" ]; then
    echo "# Mem0 Export Index" > "$INDEX"
    echo "" >> "$INDEX"
    echo "| Project | Last export | File |" >> "$INDEX"
    echo "|---|---|---|" >> "$INDEX"
  fi
  echo "| $USER_ID | $(date +%Y-%m-%d) | [[$USER_ID/memories-$(date +%Y-%m-%d)]] |" >> "$INDEX"
  ok "Index updated: $INDEX"
else
  warn "Export looks empty ($LINES lines) — check mem0 list output"
fi

echo ""
echo "Next: open Obsidian → graph view → look for new mem0-export nodes."
echo "Memory domain reminder: Mem0 = facts, Obsidian = human-reviewed knowledge."
echo "Do NOT let agents write here automatically — this is a review view."